name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v5
      
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
          
      #- name: Setup Gradle
      #  uses: gradle/actions/setup-gradle@v5    
        
      - name: Build APK
        run: ./gradlew assembleRelease
        
      #- name: Build APK
      #  uses: gradle/gradle-build-action@v2
      #  with:
      #    gradle-version: current
      #    arguments: assembleRelease
          
      - name: Sign APK
        id: sign_app
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0
          
      - name: Rename APK
        run: mv ${{steps.sign_app.outputs.signedFile}} MiWu_$GITHUB_REF_NAME.apk
        
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
          makeLatest: ${{ !contains(github.ref_name, '-dev') }}
          prerelease: ${{ contains(github.ref_name, '-dev') }}
